### POst
POST localhost:8080/customer/create
content-type: application/json

{
    "name": "John Doe",
    "job": "programmer"
}


### GET
GET localhost:8080/customer/findById?customer-id=0e77489b-a447-47b5-84c7-7788045fe366